/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_githhub_vontikov_jl_LuaEngine */

#ifndef _Included_com_githhub_vontikov_jl_LuaEngine
#define _Included_com_githhub_vontikov_jl_LuaEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_githhub_vontikov_jl_LuaEngine_init
  (JNIEnv *, jobject);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_githhub_vontikov_jl_LuaEngine_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    logLevel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_githhub_vontikov_jl_LuaEngine_logLevel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    registerFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_githhub_vontikov_jl_LuaEngine_registerFunction
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    exec
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_githhub_vontikov_jl_LuaEngine_exec__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    exec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_githhub_vontikov_jl_LuaEngine_exec__
  (JNIEnv *, jobject);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    loadScript
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_githhub_vontikov_jl_LuaEngine_loadScript
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_githhub_vontikov_jl_LuaEngine
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_githhub_vontikov_jl_LuaEngine_getLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
